name: edge_ai_governance_iam_sod
description: Thesis monorepo — edge AI governance + IAM with separation of duties (Flutter frontend).
publish_to: none
version: 0.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  openid_client: ^0.4.0
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  equatable: ^2.0.5
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
